package com.example.quicktionary.service;

import java.util.List;

public class GameData {
    public static final List<String> YELLOW_CARD_CONTENTS = List.of(
            "An object visible from here",
            "A type of profession",
            "A type of food",
            "Associated with school",
            "A type of animal",
            "Associated with parties",
            "Associated with art",
            "Associated with the beach",
            "A type of plant",
            "The title of a TV show",
            "The name of a game",
            "Associated with politics",
            "Associated with love",
            "Associated with time",
            "Associated with sports",
            "The name of a country",
            "Associated with math",
            "The name of a brand",
            "Associated with music",
            "Associated with crime",
            "Associated with literature",
            "Associated with vacations",
            "Associated with weather",
            "Associated with science",
            "Associated with space",
            "Associated with transportation",
            "Associated with the human body",
            "Associated with family",
            "Associated with money",
            "Associated with computers",
            "An item found at the office",
            "An item found in a kitchen",
            "An article of clothing",
            "The title of a movie"
    );
    public static final List<String> BLUE_CARD_CONTENTS = List.of(
            "Is three or four letters long",
            "Is a compound word",
            "Is exactly nine letters long",
            "Does not contains a double letter",
            "Is not two syllables",
            "Uses the same vowel twice",
            "Has more consonants than vowels",
            "Begins and ends with the same letter",
            "Is exactly six letters long",
            "Has exactly three vowels",
            "Has exactly four syllables",
            "Is at least ten letters long",
            "Is not exactly six letters long",
            "Is not a plural word",
            "Has at least twp different vowels",
            "Has at least three different vowels",
            "Has two vowels next to each other",
            "Is at least seven letters long",
            "Is exactly eight letters long",
            "Has exactly three syllables",
            "Has exactly two syllables",
            "Has exactly one syllable",
            "Has an equal number of vowels and consonants",
            "Is exactly seven letters long",
            "Does not contain more than one vowel",
            "Has a silent letter",
            "Does not contain two vowels next to each other",
            "Has a double consonant",
            "Does not use any letter more than once",
            "Has an even number of letters",
            "Has a double letter",
            "Does not have more than three different consonants",
            "Has an odd number of letters",
            "Is exactly five letters long"
    );
    public static final List<String> RED_CARD_CONTENTS = List.of(
            "Contains the letter CH",
            "Begins with the letter P",
            "Cannot contain the letter S",
            "Cannot contain the letter G",
            "Contains the letters NG",
            "Ends with the letter R",
            "Contains the letters MO",
            "Contains the letter K",
            "Contains the letter C",
            "Contains the letters ST",
            "Ends with the letter N",
            "Contains the letters SH",
            "Contains the letter Y",
            "Cannot contain the letter P",
            "Ends with the letter E",
            "Ends with the letter D",
            "Cannot contain the letter R",
            "Cannot contain the letter O",
            "Contains the letter PL",
            "Contains the letters OR",
            "Begins with the letter A",
            "Contains the letter W",
            "Contains the letter V",
            "Begins with the letter T",
            "Contains the letter J",
            "Cannot contain the letter L",
            "Begins with the letter S",
            "Begins with the letter F",
            "Contains the letters NT",
            "Contains the letter H",
            "Contains the letters GS",
            "Contains the letters DE",
            "Cannot contain the letter M",
            "Contains the letter B"
    );
}
